#!/bin/sh

function check_for_help () {
  if [ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "-help" ]; then
    echo "bootstrap-spackdev [DIR]"
    echo "    Installs Spack and SpackDev in DIR."
    echo "    DIR must already exist."
    echo "    If DIR is not specified, uses current directory."
    exit 1
  fi
}

function get_dir() {
  if [ -z "$1" ] ; then
    echo "empty"
    req_dir="`pwd`"
  else
    echo "full"
    req_dir="$1"
  fi
  cd "$req_dir" &&\
  dir="`/bin/pwd`" && \
  echo "using $dir for SpackDev and Spack install..."
}

function get_spack() {
  echo "checking out Spack... " && \
  git clone https://github.com/amundson/spack.git && \
  echo "done."
}

function get_spackdev() {
  echo "checking out SpackDev... " && \
  git clone https://github.com/amundson/spackdev.git && \
  echo "done."
}

function create_setup_sh() {
  echo "creating setup.sh... " && \
  echo "export PATH=\"$dir/spackdev/bin:\$PATH\"" > setup.sh && \
  echo ". \"$dir/spack/share/spack/setup-env.sh\"" >> setup.sh && \
  echo "done"
}

check_for_help "$@" &&
get_dir "$@" &&\
get_spack &&\
get_spackdev &&\
create_setup_sh &&
echo "use \". $dir/setup.sh\" to get started"
